Watching for file changes with StatReloader
Internal Server Error: /api/loadHomePage/
Traceback (most recent call last):
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/root/Exide.Backend/products/views.py", line 314, in loadHomePage
    slug=list(Product.objects.filter(id=item.product.id).values('slug'))
AttributeError: 'NoneType' object has no attribute 'id'
[26/Sep/2024 18:02:10] "GET /api/loadHomePage/ HTTP/1.1" 500 96283
Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Bad Request: /.env
[26/Sep/2024 18:22:12] "GET /.env HTTP/1.1" 400 65961
Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Bad Request: /
[26/Sep/2024 18:22:14] "POST / HTTP/1.1" 400 66244
Watching for file changes with StatReloader
Internal Server Error: /api/loadHomePage/
Traceback (most recent call last):
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/root/Exide.Backend/products/views.py", line 314, in loadHomePage
    slug=list(Product.objects.filter(id=item.product.id).values('slug'))
AttributeError: 'NoneType' object has no attribute 'id'
[26/Sep/2024 18:32:35] "GET /api/loadHomePage/ HTTP/1.1" 500 96283
[27/Sep/2024 00:03:58] "GET /media/brand/benchmark.png HTTP/1.1" 200 7640
Internal Server Error: /api/loadHomePage/
Traceback (most recent call last):
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/root/Exide.Backend/products/views.py", line 314, in loadHomePage
    slug=list(Product.objects.filter(id=item.product.id).values('slug'))
AttributeError: 'NoneType' object has no attribute 'id'
[27/Sep/2024 01:00:57] "GET /api/loadHomePage/ HTTP/1.1" 500 95929
Internal Server Error: /api/loadHomePage/
Traceback (most recent call last):
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/root/Exide.Backend/products/views.py", line 314, in loadHomePage
    slug=list(Product.objects.filter(id=item.product.id).values('slug'))
AttributeError: 'NoneType' object has no attribute 'id'
[27/Sep/2024 01:01:43] "GET /api/loadHomePage/ HTTP/1.1" 500 95929
Not Found: /robots.txt
[27/Sep/2024 01:34:57] "GET /robots.txt HTTP/1.1" 404 2551
[27/Sep/2024 01:34:59] "GET /media/products/canasafe-cover-x_0.png HTTP/1.1" 200 145277
Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Bad Request: /js/NewWindow_2_all.js
[27/Sep/2024 02:04:48] "GET /js/NewWindow_2_all.js HTTP/1.1" 400 66003
Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Bad Request: /.env
[27/Sep/2024 02:22:56] "GET /.env HTTP/1.1" 400 65888
Internal Server Error: /api/loadHomePage/
Traceback (most recent call last):
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/root/Exide.Backend/products/views.py", line 314, in loadHomePage
    slug=list(Product.objects.filter(id=item.product.id).values('slug'))
AttributeError: 'NoneType' object has no attribute 'id'
[27/Sep/2024 02:50:44] "GET /api/loadHomePage/ HTTP/1.1" 500 96187
[27/Sep/2024 02:50:55] "POST /api/getAllProducts/ HTTP/1.1" 200 25726
[27/Sep/2024 02:50:55] "GET //media/products/activarmr-80-400_0.png HTTP/1.1" 200 285076
[27/Sep/2024 02:50:55] "GET //media/category/Eye_Protection.png HTTP/1.1" 200 158572
[27/Sep/2024 02:50:55] "GET //media/products/activarmr-80-100_0.png HTTP/1.1" 200 191895
[27/Sep/2024 02:50:55] "GET //media/category/Body_Protection.png HTTP/1.1" 200 158572
[27/Sep/2024 02:50:55] "GET //media/products/activarmr-43-217_0.png HTTP/1.1" 200 326397
[27/Sep/2024 02:50:55] "GET //media/products/activarmr-97-200_0.png HTTP/1.1" 200 309238
[27/Sep/2024 02:50:56] "GET //media/category/Fall_Protection.png HTTP/1.1" 200 176666
[27/Sep/2024 02:50:56] "GET //media/category/Fire_Protection.png HTTP/1.1" 200 206480
[27/Sep/2024 02:50:56] "GET //media/category/First_Aid_Solutions.png HTTP/1.1" 200 199058
[27/Sep/2024 02:50:56] "GET //media/category/Foot_Protection.png HTTP/1.1" 200 170393
[27/Sep/2024 02:50:56] "GET //media/category/Hand_Protection.png HTTP/1.1" 200 176744
[27/Sep/2024 02:50:56] "GET //media/category/Head_Protection.png HTTP/1.1" 200 163861
[27/Sep/2024 02:50:56] "GET //media/category/Hearing_Protection.png HTTP/1.1" 200 182268
[27/Sep/2024 02:50:56] "GET //media/category/Meters_and_Detectors.png HTTP/1.1" 200 183125
[27/Sep/2024 02:50:56] "GET //media/category/Respiratory_Protection.png HTTP/1.1" 200 183125
[27/Sep/2024 02:50:56] "GET //media/category/Road_and_Safety.png HTTP/1.1" 200 139505
[27/Sep/2024 02:50:56] "GET //media/category/Welding_Protection.png HTTP/1.1" 200 179575
[27/Sep/2024 02:50:56] "GET //media/category/testing-category12.png HTTP/1.1" 200 191768
[27/Sep/2024 02:50:56] "GET //media/products/3m-full-brim-hard-hat-h-803r_0.png HTTP/1.1" 200 53697
[27/Sep/2024 02:50:56] "GET //media/products/3m-full-brim-hard-hat-h-801r_0.png HTTP/1.1" 200 48936
[27/Sep/2024 02:50:56] "GET //media/products/3m-g3000-non-vented_0.png HTTP/1.1" 200 104430
[27/Sep/2024 02:50:56] "GET //media/products/3m-g3000-vented_0.png HTTP/1.1" 200 87795
[27/Sep/2024 02:50:56] "GET //media/products/3m-1100-foam-earplug-uncorded_0.png HTTP/1.1" 200 107254
[27/Sep/2024 02:50:56] "GET //media/products/3m-1110-foam-earplug-corded_0.png HTTP/1.1" 200 83169
[27/Sep/2024 02:50:56] "GET //media/products/3m-310-1001_0.png HTTP/1.1" 200 158542
[27/Sep/2024 02:50:56] "GET //media/products/3m-lite-com-ii_0.png HTTP/1.1" 200 218619
[27/Sep/2024 02:50:56] "GET //media/products/3m-peltor-h7-bfpe3-series_0.png HTTP/1.1" 200 191732
[27/Sep/2024 02:50:56] "GET //media/products/honeywell-bw-clip-single-gas_0.png HTTP/1.1" 200 89157
[27/Sep/2024 02:50:56] "GET //media/products/honeywell-bw-max-xt-ii_0.png HTTP/1.1" 200 74903
[27/Sep/2024 02:50:56] "GET //media/products/honeywell-bw-micro-clip-xl_0.png HTTP/1.1" 200 217371
[27/Sep/2024 02:50:56] "GET //media/products/honeywell-bw-quattro_0.png HTTP/1.1" 200 159349
[27/Sep/2024 02:50:56] "GET //media/products/honeywell-bw-micro-clip-xt_0.png HTTP/1.1" 200 181973
[27/Sep/2024 02:50:56] "GET //media/products/canasafe-pocket-lite_0.png HTTP/1.1" 200 88323
[27/Sep/2024 02:50:56] "GET //media/products/canasafe-caplite_0.png HTTP/1.1" 200 83169
[27/Sep/2024 02:50:56] "GET //media/products/portwest-berlin-executive-vest_0.png HTTP/1.1" 200 126154
[27/Sep/2024 02:50:56] "GET //media/products/eurosafe-leather-welding-leg-g_0.png HTTP/1.1" 200 151178
[27/Sep/2024 02:50:56] "GET //media/products/3m-334-anti-fog_0.png HTTP/1.1" 200 107259
[27/Sep/2024 02:50:56] "GET //media/products/3m-linte-cinza-grey_0.png HTTP/1.1" 200 53697
[27/Sep/2024 02:50:56] "GET //media/products/canasafe-latch-201_0.png HTTP/1.1" 200 336473
[27/Sep/2024 02:50:56] "GET //media/products/canasafe-latch-101_0.png HTTP/1.1" 200 291551
[27/Sep/2024 02:50:56] "GET //media/products/canasafe-pascal-16_0.png HTTP/1.1" 200 181973
[27/Sep/2024 02:50:56] "GET //media/products/canasafe-pascal-9_0.png HTTP/1.1" 200 160557
[27/Sep/2024 02:50:56] "GET //media/products/canasafe-cover-x_0.png HTTP/1.1" 200 145277
[27/Sep/2024 02:50:56] "GET //media/products/3m-h700v-vented_0.png HTTP/1.1" 200 240531
[27/Sep/2024 02:50:56] "GET //media/products/3m-peltor-h7-bfpe3-series-2_0.png HTTP/1.1" 200 139273
[27/Sep/2024 02:50:56] "GET //media/products/3mtm-protective-coverall-4520_0.png HTTP/1.1" 200 104430
[27/Sep/2024 02:50:56] "GET //media/products/3m-full-brim-hard-hat-h-802r-4_0.png HTTP/1.1" 200 91546
[27/Sep/2024 02:50:56] "GET //media/products/3m-aura-9332-valved-particulat_0.png HTTP/1.1" 200 151178
[27/Sep/2024 02:50:56] "GET //media/products/3m-aura-9312-ffp1-particulate_0.png HTTP/1.1" 200 167937
[27/Sep/2024 02:50:56] "GET //media/products/3m-9010v-particulate-respirato_0.png HTTP/1.1" 200 193321
[27/Sep/2024 02:50:56] "GET //media/products/3mtm-6001-organic-vapor-perfor_0.png HTTP/1.1" 200 137189
[27/Sep/2024 02:50:56] "GET //media/products/3mtm-ammonia-methylamine-cartr_0.png HTTP/1.1" 200 152442
[27/Sep/2024 02:50:56] "GET //media/products/eurosafe-twill-cotton-ultralit_0.png HTTP/1.1" 200 124278
[27/Sep/2024 02:50:56] "GET //media/products/3mtm-particulate-welding-respi_0.png HTTP/1.1" 200 146717
[27/Sep/2024 02:50:56] "GET //media/products/3mtm-speedglas-9100-fx-welding_0.png HTTP/1.1" 200 151695
[27/Sep/2024 02:50:56] "GET //media/products/eurosafe-leather-welding-apron_0.png HTTP/1.1" 200 197351
[27/Sep/2024 02:50:56] "GET //media/products/bullard-ltxrd_0.png HTTP/1.1" 200 175997
[27/Sep/2024 02:50:56] "GET //media/products/100-cotton-coverall-w-reflecti_0.png HTTP/1.1" 200 98654
[27/Sep/2024 02:50:57] "GET //media/products/bulldozer-fireman-suit_0.png HTTP/1.1" 200 240531
[27/Sep/2024 02:50:57] "GET //media/products/absolute-extreme-light-mid-cut_0.png HTTP/1.1" 200 172715
[27/Sep/2024 02:50:57] "GET //media/products/alice-s3-src-womens-shoes-prod_0.png HTTP/1.1" 200 139273
[27/Sep/2024 02:50:57] "GET //media/products/3m-reusable-cord-earplug-us-wi_0.png HTTP/1.1" 200 157813
[27/Sep/2024 02:50:57] "GET //media/products/ringers-r065_0.png HTTP/1.1" 200 164632
[27/Sep/2024 02:50:57] "GET //media/products/riley-kosma-clear_0.png HTTP/1.1" 200 163951
[27/Sep/2024 02:50:57] "GET //media/products/3mtm-half-facepiece-reusable-r_0.png HTTP/1.1" 200 41645
[27/Sep/2024 02:50:57] "GET //media/products/3mtm-organic-vaporacid-gas-car_0.png HTTP/1.1" 200 44217
Internal Server Error: /api/loadHomePage/
Traceback (most recent call last):
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/root/Exide.Backend/products/views.py", line 314, in loadHomePage
    slug=list(Product.objects.filter(id=item.product.id).values('slug'))
AttributeError: 'NoneType' object has no attribute 'id'
[27/Sep/2024 02:50:59] "GET /api/loadHomePage/ HTTP/1.1" 500 96187
[27/Sep/2024 03:30:09] "GET /media/brand/promax.jpg HTTP/1.1" 200 3939
Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Bad Request: /.env
[27/Sep/2024 04:33:24] "GET /.env HTTP/1.1" 400 65800
Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Bad Request: /.git/config
[27/Sep/2024 05:11:16] "GET /.git/config HTTP/1.1" 400 65880
Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Bad Request: /
[27/Sep/2024 05:31:30] "GET / HTTP/1.1" 400 65801
Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Bad Request: /.git/config
[27/Sep/2024 05:50:56] "GET /.git/config HTTP/1.1" 400 65880
Internal Server Error: /api/loadHomePage/
Traceback (most recent call last):
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/root/Exide.Backend/products/views.py", line 314, in loadHomePage
    slug=list(Product.objects.filter(id=item.product.id).values('slug'))
AttributeError: 'NoneType' object has no attribute 'id'
[27/Sep/2024 06:00:43] "GET /api/loadHomePage/ HTTP/1.1" 500 96295
Internal Server Error: /api/loadHomePage/
Traceback (most recent call last):
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/root/Exide.Backend/products/views.py", line 314, in loadHomePage
    slug=list(Product.objects.filter(id=item.product.id).values('slug'))
AttributeError: 'NoneType' object has no attribute 'id'
[27/Sep/2024 06:00:48] "GET /api/loadHomePage/ HTTP/1.1" 500 96295
Internal Server Error: /api/loadHomePage/
Traceback (most recent call last):
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/root/Exide.Backend/products/views.py", line 314, in loadHomePage
    slug=list(Product.objects.filter(id=item.product.id).values('slug'))
AttributeError: 'NoneType' object has no attribute 'id'
[27/Sep/2024 06:02:31] "GET /api/loadHomePage/ HTTP/1.1" 500 96295
Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Bad Request: /.git/config
[27/Sep/2024 07:04:50] "GET /.git/config HTTP/1.1" 400 65682
Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Bad Request: /.git/config
[27/Sep/2024 07:04:51] "GET /.git/config HTTP/1.1" 400 65682
Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Bad Request: /
[27/Sep/2024 08:00:53] "GET / HTTP/1.1" 400 65662
Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '157.173.218.83'. You may need to add '157.173.218.83' to ALLOWED_HOSTS.
Bad Request: /.git/config
[27/Sep/2024 10:30:35] "GET /.git/config HTTP/1.1" 400 65880
[27/Sep/2024 11:48:48] "GET /media/products/canasafe-pascal-9_0.png HTTP/1.1" 200 160557
Internal Server Error: /api/loadHomePage/
Traceback (most recent call last):
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/Exide.Backend/.venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/root/Exide.Backend/products/views.py", line 314, in loadHomePage
    slug=list(Product.objects.filter(id=item.product.id).values('slug'))
AttributeError: 'NoneType' object has no attribute 'id'
[27/Sep/2024 13:59:17] "GET /api/loadHomePage/ HTTP/1.1" 500 96282
